networks:
    frontend:
        external: false

volumes:
    haproxy_certs:
        external: false

services:
    haproxy:
        image: haproxy:2.8-alpine
        restart: unless-stopped
        ports:
            - "53:53"
            - "443:8000/tcp"
            - "3478:3478"
            - "4464:4464/tcp"
            - "7881:7881/tcp"
            - "22124:22124/udp"
            - "50000-51000:50000-51000/udp"
            - "61000-62000:61000-62000/udp"
        environment:
            - JACKTRIP_HA_HOST=REPLACE_WITH_HAPROXY_FQDN
            - JACKTRIP_HA_IP=REPLACE_WITH_HAPROXY_IP
            - JACKTRIP_S1_IP=REPLACE_WITH_STUDIO_1_FQDN
            - JACKTRIP_S2_IP=REPLACE_WITH_STUDIO_2_FQDN
            - JACKTRIP_DNS1_IP=1.1.1.1
            - JACKTRIP_DNS2_IP=9.9.9.9
        volumes:
            - ./ha-proxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
            - ./haproxy_certs/certs.pem:/haproxy/certs.pem:ro
        command: sh -c "apk update && apk add --upgrade apk-tools && apk upgrade --available && printf '#!/bin/sh\nservice haproxy stop\n' > /etc/letsencrypt/renewal-hooks/pre/haproxy.sh && printf '#!/bin/sh\nservice haproxy start\n' > /etc/letsencrypt/renewal-hooks/post/haproxy.sh && chmod 755 /etc/letsencrypt/renewal-hooks/pre/haproxy.sh && chmod 755 /etc/letsencrypt/renewal-hooks/post/haproxy.sh && haproxy reload"
        container_name: haproxy
        networks:
            frontend:
                aliases:
                    - haproxy
